### ISSUE TITLE
how is bitbank

### ISSUE THREAD

**Issue by lnguyen** [lutzleonhardt/bitbank-gekko#2]
ive been looking into bitbank, I was wondering your experience, if it's worth it

**Comment by lutzleonhardt** [comment]
Hi lnguyen,

in my opinion the BitBank prediction algorithm has a lot of potential, because it uses the orderbook and not the classical candles to predict the future.
Now we try to find the best strategy to advice short and longs depending on the predicted data. We use gekko to run the backtests.
BitBank now supports additional featureset values (volatility/standard deviations) which we want to use to get the best results.
Another try would be to combine the prediction algorithm with the technical analysis (MACD, RSI, etc.) and some kind of genetic algorithm. But we will see.

I think @lee101 is able to elaborate it a little bit deeper than me.

**Comment by lnguyen** [comment]
Thanks for reply! I play with Gekko and different strategies and came across yours. It might be interesting to combine some TA with Bitbank.

**Comment by lee101** [comment]
Hi @lnguyen, 

Sign up and have a try i'm happy to extend you some time if required :) 

The value BitBank.nz can provide to you also depends on your capital/risk profile just like any trading venture so i'm happy to negotiate a better price :)

The overview of the forecasts for every market we have (from poloniex) should help you see if there are any upcoming coins or anomalies in particular markets https://bitbank.nz/coins
 
you can dig into a specific market and see graphs/live predictions of our forecasts over time, often our customers find value in just seeing a more detailed chart than what the exchanges provide (dense data updated every 5-20 seconds helps you to see trends better than when things aren't grouped into 1m-1hr bars).

Most of the value can also come from the forecasts, we try to be as transparent as possible with the prediction accuracy and methods to help build trust and educate our customers on how to develop good automated trading strategies :)

Id say BitBank.nz is more focused on high frequency short term predictions and is more API and developer friendly than most of our competitors. i have done a bit of analysis of our competitors too including open source bots if that's useful in making a decision http://blog.bitbank.nz/comparing-crypto-trading-companies/

Happy trading :) all the best.
